import time

name = input("What is your name? ")
start_quit = input(f"Welcome {name}, today we tell an old tale. Do you want to play along?  ").lower()

if start_quit == "no":
    print("Eh your loss. Goodbye.")
    quit()
elif start_quit == "yes":
    print('This tale starts with miller who had a beautiful daughter,')
    time.sleep(2)
    print('and when she was grown up he became anxious that she should be well married and taken care of; ')
    time.sleep(2)
    print('so he thought, "If a decent sort of man comes and asks her in marriage, I will give her to him."')
    time.sleep(2)
    print('Soon after a suitor came forward who seemed very well to do, ')
    time.sleep(2)
    print('and as the miller knew nothing to his disadvantage, he promised him his daughter.')
    time.sleep(2)
    print('But the girl did not seem to love him as a bride should love her bridegroom;')
    time.sleep(2)
    print('she had no confidence in him; as often as she saw him or thought about him, she felt a chill at her heart.')
    time.sleep(2)
    print('She grew more anxious by the day, the wedding date was closing in and she knew nothing of her bridgroom.')
    time.sleep(1) 

while True:    
    talk_dont = input('One day she saw him stand by the well behind her house, should she go and talk to him or keep avoiding him?(avoid/talk) ').lower()

    if talk_dont == 'avoid':
        print("She moved about her day, and soon after the wedding-day came,")
        time.sleep(2) 
        print('the friends and neighbours assembled, the miller having invited them, and the bridegroom also appeared.')
        time.sleep(2)
        print("That day the bride told no stories, for there were none left for her.")
        time.sleep(2)
        print("After they cermony, the bride and the bridegroom left for his home- upon arriving at the house she concluded it was no home.")
        time.sleep(2)
        print("For it lacked the wamrth of a home. Her husband- who she could not look in the eyes of offered her a white drink.")
        time.sleep(2)
        print("he showed her around the house but there wasn't much to look at. For it was a big house but it contained no furniture or accessories.")
        time.sleep(2)
        print("except... for dark heavy curtains all about the house. Her husband then offered her a second- red- and a third- white drink. ")
        time.sleep(2)
        print("It all went dark and next thing she knew she was in circular place. Too small for her liking.")
        time.sleep(2)
        print("She felt a sharp sting on her back and when she felt around she realized the thing she was in was heating up gradually.")
        time.sleep(2)
        print("The last sounds she heard was of deafening laughter from outside and her own shrieking echoing in the pot. The end.")
        quit()
    elif talk_dont == 'talk':
        print('She walked up to him with no plan- grateful he spoke first "You know you are to be my bride, and yet you have never been to see me."')
        time.sleep(2)
        print('She said "I do not know where your house is." Then he replied "My house is a long way in the wood."')
        time.sleep(2)
        print("She began to make excuses, and said she could not find the way to it; but the bridegroom said,")
        time.sleep(2)
        print('"You must come and pay me a visit next Sunday; I have already invited company, and I will strew ashes on the path through the wood, so that you will be sure to find it."')
        time.sleep(2)
        print("When Sunday came, and the girl set out on her way, she felt very uneasy without knowing exactly why; ")
        
        while True:
            peas_or_not = input("Will you pick up the peas and lentil?(yes/no) ").lower()
            
            if peas_or_not == 'no':
                print("There were ashes strewed on the path through the wood, just as he had promised.")
                time.sleep(2)
                print("She went on the whole day until she came to the middle of the wood, where it was the darkest, and there stood a lonely house, ")
                time.sleep(2)
                print("not pleasant in her eyes, for it was dismal and unhomelike.")
                time.sleep(2)
                print("She walked in, but there was no one there, and the greatest stillness reigned. Suddenly she heard a voice cry, ")
                time.sleep(2)
                print('"Turn back, turn back, thou pretty bride, Within this house thou must not bide, For here do evil things betide."')
                time.sleep(2)
                print("The girl glanced round, and perceived that the voice came from a bird who was hanging in a cage by the wall. And again it cried, ")
                time.sleep(2)
                print('"Turn back, turn back, thou pretty bride, Within this house thou must not bide, For here do evil things betide."')
                time.sleep(2)
                print("The pretty bride ignored the bird and went on from one room into another through the whole house, but it was quite empty, and no soul to be found in it.")
                time.sleep(2)
                
                while True:
                    celler_go_dont = input("At last she reached the cellar, leave or go inside?(leave/go inside) ").lower()

                    if celler_go_dont == 'leave':
                        print("She moves on from the dark door of the celler. As she continues her exploring she hears footsteps from outside and a group of robbers walk in along with her bridegroom.")
                        time.sleep(2)
                        print("It all went dark and next thing she knew she was in circular place. Too small for her liking.")
                        time.sleep(2)
                        print("She felt a sharp sting on her back and when she felt around she realized the thing she was in was heating up gradually.")
                        time.sleep(2)
                        print("The last sounds she heard was of deafening laughter from outside and her own shriek echoing in the pot. The end.")
                        quit()

                    elif celler_go_dont == 'go inside':
                        print('there sat a very old woman in the middle of the room, nodding her head. "Can you tell me," said the bride, "if my bridegroom lives here?"')
                        time.sleep(2)
                        print(' "Oh, poor child," answered the old woman,')
                        time.sleep(2)
                        print('"do you know what has happened to you? You are in a place of cutthroats. You thought you were a bride, and soon to be married,')
                        time.sleep(2)
                        print('but death will be your spouse. Look here, I have a great kettle of water to set on,')
                        time.sleep(1)
                        print('and when once they have you in their power they will cut you in pieces without mercy, cook you, and eat you, for they are cannibals.')
                        time.sleep(2)
                        print('Unless I have pity on you, and save you, all is over with you!"')
                        time.sleep(1)
                        
                        while True:
                            ask_hide = input("The old woman then asks her to hide behind the great cask. Will she ask the old woman about her bridegroom's whereabouts again or hide?(ask/hide) ")
                            
                            if ask_hide == 'ask':
                                print("She continued to pester the old woman about her bridegroom. Before it was settled than a group of robbers entered the house. With her bridegroom trailing behind, ")
                                time.sleep(2)
                                print('They brought another young woman with them, dragging her along, upon looking at her the bridegroom said "Looks like it is feast day!". The rest... well I am sure you understand by now')
                                quit()

                            elif ask_hide == 'hide':
                                print('Then the old woman hid her behind a great cask, where she could not be seen.')
                                time.sleep(1)
                                print('"Be as still as a mouse," said she; "do not move or go away, or else you are lost.')
                                time.sleep(2)
                                print('At night, when the robbers are asleep, we will escape. I have been waiting a long time for an opportunity."')
                                time.sleep(1)                        
                                print('No sooner was it settled than the wicked gang entered the house.')
                                time.sleep(1)
                                print('They brought another young woman with them, dragging her along, and they were drunk, and would not listen to her cries and groans.')
                                time.sleep(2)
                                print('They gave her wine to drink, three glasses full, one of white wine, one of red, and one of yellow, and then they cut her in pieces.')
                                time.sleep(2)
                                print('The poor bride all the while shaking and trembling when she saw what a fate the robbers had intended for her.')
                                time.sleep(2)
                                print('One of them noticed on the little finger of their victim a golden ring, and as he could not draw it off easily,')
                                time.sleep(2)                              
                                print("he took an axe and chopped it off, but the finger jumped away, and fell behind the cask on the bride's lap.")
                                time.sleep(2)
                                print('The robber took up a light to look for it, but he could not find it. Then said one of the others,')
                                time.sleep(1)
                                print('"Have you looked behind the great cask?" But the old woman cried, "Come to supper, and leave off looking till to-morrow; the finger cannot run away."')
                                time.sleep(2)

                                while True:
                                    pocket_not = input("Pocket finger or not?(pocket/dont) ")
                           
                                    print('Then the robbers said the old woman was right, and they left off searching, and sat down to eat, and the old woman dropped some sleeping stuff into their wine,')
                                    time.sleep(2)
                                    print('so that before long they stretched themselves on the cellar floor, sleeping and snoring.')
                                    time.sleep(1)
                                    print('When the bride heard that, she came from behind the cask, and had to make her way among the sleepers lying all about on the ground,')
                                    time.sleep(2)
                                    print('and she felt very much afraid lest she might awaken any of them. But by good luck she passed through, and the old woman with her,')
                                    time.sleep(2)
                                    print('and they opened the door, and they made all haste to leave that house of murderers.')
                                    time.sleep(1)
                                    print('The wind had carried away the ashes from the path, as she ran into the dark, she realised the grave miatake she had made.')
                                    time.sleep(2)
                                    print('Oh! How she wished she had used the peas and lentil to make her own path back.')
                                    time.sleep(2)
                                    print('Hours.. or perhaps days went by and yet they found no path home. I am sure you can guess how that one ended. Let me help: Dehydration')
                                    quit()
                              
                            else:
                                print("Invalid input.")

                    else:
                        print("Invalid input.")

            elif peas_or_not == 'yes':
                    print("She filled both pockets full of peas and lentils. There were ashes strewed on the path through the wood, ")
                    time.sleep(1)
                    print('but, nevertheless, at each step she cast to the right and left a few peas on the ground.')
                    time.sleep(1)
                    print("She went on the whole day until she came to the middle of the wood, where it was the darkest, and there stood a lonely house, ")
                    time.sleep(2)
                    print("not pleasant in her eyes, for it was dismal and unhomelike.")
                    time.sleep(1)
                    print("She walked in, but there was no one there, and the greatest stillness reigned. Suddenly she heard a voice cry, ")
                    time.sleep(1)
                    print('"Turn back, turn back, thou pretty bride, Within this house thou must not bide, For here do evil things betide."')
                    time.sleep(1)
                    print("The girl glanced round, and perceived that the voice came from a bird who was hanging in a cage by the wall. And again it cried, ")
                    time.sleep(2)
                    print('"Turn back, turn back, thou pretty bride, Within this house thou must not bide, For here do evil things betide."')
                    time.sleep(1)
                    print("The pretty bride ignored the bird and went on from one room into another through the whole house, but it was quite empty, and no soul to be found in it.")
                    time.sleep(1)
                    
                    while True:
                        celler_go_dont = input("At last she reached the cellar, leave or go inside?(leave/go inside) ").lower()

                        if celler_go_dont == 'leave':
                            print("She moves on from the dark door of the celler. As she continues her exploring she hears footsteps from outside and a group of robbers walk in along with her bridegroom.")
                            time.sleep(1)
                            print("It all went dark and next thing she knew she was in circular place. Too small for her liking.")
                            time.sleep(1)
                            print("She felt a sharp sting on her back and when she felt around she realized the thing she was in was heating up gradually.")
                            time.sleep(2)
                            print("The last sounds she heard was of deafening laughter from outside and her own shrieking echoing in the pot. The end.")
                            quit()

                        elif celler_go_dont == 'go inside':
                            print('there sat a very old woman in the middle of the room, nodding her head. "Can you tell me," said the bride, "if my bridegroom lives here?"')
                            time.sleep(2)
                            print(' "Oh, poor child," answered the old woman,')
                            time.sleep(1)
                            print('"do you know what has happened to you? You are in a place of cutthroats. You thought you were a bride, and soon to be married,')
                            time.sleep(2)
                            print('but death will be your spouse. Look here, I have a great kettle of water to set on, ')
                            time.sleep(2)
                            print('and when once they have you in their power they will cut you in pieces without mercy, cook you, and eat you, for they are cannibals.')
                            time.sleep(2)
                            print('Unless I have pity on you, and save you, all is over with you!"')
                            time.sleep(1)
                            
                            while True:
                                ask_hide = input("The old woman then asks her to hide behind the great cask. Will she ask the old woman about her bridegroom's whereabouts again or hide?(ask/hide) ")
                                
                                if ask_hide == 'ask':
                                    print("She continued to pester the old woman about her bridegroom. Before it was settled than a group of robbers entered the house. With her bridegroom trailing behind, ")
                                    time.sleep(2)
                                    print('They brought another young woman with them, dragging her along, upon looking at her the bridegroom said "Looks like it is feast day!". The rest... well I am sure you understand by now')
                                    quit()

                                elif ask_hide == 'hide':
                                    print('Then the old woman hid her behind a great cask, where she could not be seen.')
                                    time.sleep(1)
                                    print('"Be as still as a mouse," said she; "do not move or go away, or else you are lost.')
                                    time.sleep(1)
                                    print('At night, when the robbers are asleep, we will escape. I have been waiting a long time for an opportunity."')
                                    time.sleep(1)                        
                                    print('No sooner was it settled than the wicked gang entered the house.')
                                    time.sleep(1)
                                    print('They brought another young woman with them, dragging her along, and they were drunk, and would not listen to her cries and groans.')
                                    time.sleep(2)
                                    print('They gave her wine to drink, three glasses full, one of white wine, one of red, and one of yellow, and then they cut her in pieces.')
                                    time.sleep(2)
                                    print('The poor bride all the while shaking and trembling when she saw what a fate the robbers had intended for her.')
                                    time.sleep(1)
                                    print('One of them noticed on the little finger of their victim a golden ring, and as he could not draw it off easily,')
                                    time.sleep(1)                              
                                    print("he took an axe and chopped it off, but the finger jumped away, and fell behind the cask on the bride's lap.")
                                    time.sleep(1)
                                    print('The robber took up a light to look for it, but he could not find it. Then said one of the others,')
                                    time.sleep(1)
                                    print('"Have you looked behind the great cask?" But the old woman cried, "Come to supper, and leave off looking till to-morrow; the finger cannot run away."')
                                    time.sleep(2)

                                    while True:
                                        pocket_not = input("Pocket finger or not?(pocket/dont) ")

                                        if pocket_not == 'dont':
                                            print('Then the robbers said the old woman was right, and they left off searching, and sat down to eat, and the old woman dropped some sleeping stuff into their wine,')
                                            time.sleep(2)
                                            print('so that before long they stretched themselves on the cellar floor, sleeping and snoring.')
                                            time.sleep(1)
                                            print('When the bride heard that, she came from behind the cask, and had to make her way among the sleepers lying all about on the ground,')
                                            time.sleep(2)
                                            print('and she felt very much afraid lest she might awaken any of them. But by good luck she passed through, and the old woman with her,')
                                            time.sleep(2)
                                            print('and they opened the door, and they made all haste to leave that house of murderers.')
                                            time.sleep(1)
                                            print('The wind had carried away the ashes from the path, but the peas and lentils had budded and sprung up, and the moonshine upon them showed the way.')
                                            time.sleep(2)
                                            print('they went on through the night, till in the morning they reached the mill.')
                                            time.sleep(1)
                                            print('Then the girl related to her father all that had happened to her.')
                                            time.sleep(1)                                          
                                            print('Her father was skeptical and asked her for proof. He believed not a word, spoken by his daughter nor the old woman.')
                                            time.sleep(2)
                                            print("He assumed his daughter crazy and decided to rush the wedding.")
                                            time.sleep(1)
                                            print("The wedding-day came, the friends and neighbours assembled, the miller having invited them, and the bridegroom also appeared.")
                                            time.sleep(2)
                                            print("When they were all seated at table, each one had to tell a story. But the bride sat still,")
                                            time.sleep(1)
                                            print("That day she told no stories, for she had lost her voice screaming her truth with no one to hear.")
                                            time.sleep(1)
                                            print("When she had reached out to authorities, and they searched the woods for the bridegroom's house and came out empty handed,")
                                            time.sleep(2)
                                            print("she knew her fate was sealed.")
                                            time.sleep(1)
                                            print("Her father too grateful, the bridegroom still accepted her.")
                                            time.sleep(1)
                                            print("The rest, I am sure you can guess by now. The end.")
                                            print("You lose.")
                                            quit()
                                                                                  
                                        elif pocket_not == 'pocket':
                                            print('Then the robbers said the old woman was right, and they left off searching, and sat down to eat, and the old woman dropped some sleeping stuff into their wine,')
                                            time.sleep(2)
                                            print('so that before long they stretched themselves on the cellar floor, sleeping and snoring.')
                                            time.sleep(1)
                                            print('When the bride heard that, she came from behind the cask, and had to make her way among the sleepers lying all about on the ground,')
                                            time.sleep(2)
                                            print('and she felt very much afraid lest she might awaken any of them. But by good luck she passed through, and the old woman with her,')
                                            time.sleep(2)
                                            print('and they opened the door, and they made all haste to leave that house of murderers.')
                                            time.sleep(1)
                                            print('The wind had carried away the ashes from the path, but the peas and lentils had budded and sprung up, and the moonshine upon them showed the way.')
                                            time.sleep(2)
                                            print('they went on through the night, till in the morning they reached the mill.')
                                            time.sleep(1)
                                            print('Then the girl related to her father all that had happened to her.')
                                            time.sleep(1)
                                            print('When the wedding-day came, the friends and neighbours assembled, the miller having invited them, and the bridegroom also appeared.')
                                            time.sleep(2)
                                            print('When they were all seated at table, each one had to tell a story. But the bride sat still, and said nothing, till at last the bridegroom said to her,')
                                            time.sleep(2)
                                            print('"Now, sweetheart, do you know no story? Tell us something."')
                                            time.sleep(1)
                                            print('She answered, "I will tell you my dream. I was going alone through a wood, and I came at last to a house in which there was no living soul,')
                                            time.sleep(2)
                                            print('but by the wall was a bird in a cage, who cried,')
                                            time.sleep(1)
                                            print('"Turn back, turn back, thou pretty bride, Within this house thou must not bide, For evil things do here betide."')
                                            time.sleep(1)
                                            print('And then again it said it. Sweetheart, the dream is not ended. Then I went through all the rooms,')
                                            time.sleep(1)
                                            print('and they were all empty, and it was so lonely and wretched.')
                                            time.sleep(1)
                                            print('At last I went down into the cellar, and there sat an old old woman, nodding her head.')
                                            time.sleep(1)
                                            print("I asked her if my bridegroom lived in that house, and she answered, ' Ah, poor child, you have come into a place of cut-throats;")
                                            time.sleep(2)
                                            print("your bridegroom does live here, but he will kill you and cut you in pieces, and then cook and eat you.'")
                                            time.sleep(1)
                                            print('Sweetheart, the dream is not ended. But the old woman hid me behind a great cask,')
                                            time.sleep(1)
                                            print('and no sooner had she done so than the robbers came home, dragging with them a young woman,')
                                            time.sleep(1)
                                            print('and they gave her to drink wine thrice, white, red, and yellow.')
                                            time.sleep(1)
                                            print("Sweetheart, the dream is not yet ended.")
                                            time.sleep(1)
                                            print('And then they killed her, and cut her in pieces. Sweetheart, my dream is not yet ended.')
                                            time.sleep(1)
                                            print('And one of the robbers saw a gold ring on the finger of the young woman, and as it was difficult to get off,')
                                            time.sleep(1)
                                            print('he took an axe and chopped off the finger, which jumped upwards,')
                                            time.sleep(1)
                                            print('and then fell behind the great cask on my lap. And here is the finger with the ring!"')
                                            time.sleep(1)
                                            print('At these words she drew it forth, and showed it to the company.')
                                            time.sleep(1)
                                            print('The robber, who during the story had grown deadly white,')
                                            time.sleep(1)
                                            print('sprang up, and would have escaped, but the folks held him fast, and delivered him up to justice.')
                                            time.sleep(1)
                                            print('And he and his whole gang were, for their evil deeds, condemned and executed')
                                            time.sleep(1)
                                            print("yeeaah you've reached the end. The happy ending you get I guess. You win.")
                                            quit()

                                        else:
                                            print('Invalid input.')
                                            continue                                   
            break   
    else:
        print("Invalid option.")
        continue